[module]
name = "fimo_core"
version = "0.1.0"

[[profile]]
name = "rust"
default = true
loader = "fimo::module::loader::rust"
exclude = ["fimo_core.rlib", "libfimo_core.rlib"]

[profile.builder]
name = "cargo"
args = ["--features", "rust_module"]

[[profile.export]]
name = { name = "fimo_core" }
version = "0.1.0-unstable+0"
extensions = []
