[package]
name = "fimo_version_core"
version = "0.1.0"
edition = "2018"
description = "Fimo version utilities"
license = "MIT OR Apache-2.0"
categories = ["game-development"]

[dependencies]
regex = "1.4.3"
numtoa = "0.2.3"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"], optional = true }
