[package]
name = "fimo_tasks"
version = "0.1.0"
edition = "2021"
description = "Fimo engine task runtime"
license = "MIT OR Apache-2.0"
categories = ["game-development"]

[lib]
crate-type = ["lib", "dylib"]

[dependencies]

[dev-dependencies]
module_loading = { path = "../../test_utilities/module_loading" }