#ifndef FIMO_IMPL_MACROS_MSVC_SAL_H
#define FIMO_IMPL_MACROS_MSVC_SAL_H

#ifdef _MSC_VER
#ifdef _USE_ATTRIBUTES_FOR_SAL
#undef _USE_ATTRIBUTES_FOR_SAL
#endif
#define _USE_ATTRIBUTES_FOR_SAL 1
#include <sal.h>
#endif

#endif // !FIMO_IMPL_MACROS_MSVC_SAL_H
