[package]
name = "fimo_actix"
version = "0.1.0"
edition = "2021"
description = "fimo-actix module"
license = "MIT OR Apache-2.0"
categories = ["game-development"]

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
parking_lot = "0.11"
fimo_version_core = { version = "0.1.0", path = "../../utilities/fimo_version_core" }
fimo_generic_module = { version = "0.1.0", path = "../../utilities/fimo_generic_module" }
fimo_actix_interface = { version = "0.1.0", path = "../../utilities/fimo_actix_interface" }
fimo_ffi_core = { version = "0.1.0", path = "../../utilities/fimo_ffi_core", optional = true }
fimo_module_core = { version = "0.1.0", path = "../../utilities/fimo_module_core", optional = true }
fimo_core_interface = { version = "0.1.0", path = "../../utilities/fimo_core_interface", optional = true }

[dev-dependencies]
reqwest = { version = "0.11.4", features = ["blocking"] }
module_loading = { path = "../../test_utilities/module_loading", features = ["actix_module"] }

[features]
default = ["rust_module"]
module = ["fimo_ffi_core", "fimo_module_core", "fimo_core_interface"]
rust_module = ["module"]