[module]
name = "fimo_actix"
version = "0.1.0"

[[profile]]
name = "rust"
default = true
loader = "fimo::module::loader::rust"
exclude = ["fimo_actix.rlib", "libfimo_actix.rlib"]

[profile.builder]
name = "cargo"
args = ["--features", "module"]

[[profile.export]]
name = { name = "fimo_actix" }
version = "0.1.0-unstable+0"
extensions = []
