// Machine generated
#define FIMO_CONTEXT_VERSION_MAJOR 0
#define FIMO_CONTEXT_VERSION_MINOR 0
#define FIMO_CONTEXT_VERSION_PATCH 0
#define FIMO_CONTEXT_VERSION_PRE NULL
#define FIMO_CONTEXT_VERSION_PRE_LEN 0
#define FIMO_CONTEXT_VERSION_BUILD NULL
#define FIMO_CONTEXT_VERSION_BUILD_LEN 0
