[package]
name = "fimo_generic_module"
version = "0.1.0"
edition = "2018"
description = "Implementation of generic modules and module instances"
license = "MIT OR Apache-2.0"
categories = ["game-development"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.11.1"
fimo_ffi = { version = "0.1.0", path = "../fimo_ffi" }
fimo_module_core = { version = "0.1.0", path = "../fimo_module_core" }
fimo_core_interface = { version = "0.1.0", path = "../../interfaces/fimo_core_interface" }