[package]
name = "fimo_module"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Fimo module definitions"
categories = ["game-development"]

[dependencies]
petgraph = "0.6"
serde_json = "1.0"
libloading = "0.7.0"
serde = { version = "1.0.123", features = ["derive"] }
fimo_ffi = { version = "0.1.0", path = "../fimo_ffi" }
