[package]
name = "fimo_module"
version = "0.1.0"
edition = "2018"
description = "Fimo module definitions"
license = "MIT OR Apache-2.0"
categories = ["game-development"]

[dependencies]
serde_json = "1.0"
tempfile = "3.3.0"
libloading = "0.7.0"
parking_lot = "0.11.1"
static_assertions = "1.1.0"
serde = { version = "1.0.123", features = ["derive"] }
fimo_ffi = { version = "0.1.0", path = "../fimo_ffi" }

[build-dependencies]
rustc_version = "0.4.0"
