[package]
name = "fimo_std"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = "Standard library of the fimo engine"
links = "fimo_std"

[lints]
workspace = true

[dependencies.paste]
version = "1.0.14"

[build-dependencies.cmake]
version = "0.1.5"

[build-dependencies.bindgen]
version = "0.69.1"

[build-dependencies.doxygen-rs]
version = "0.4.2"
